### PR TITLE
Update dependencies for .NET Core 3.1

### PR DESCRIPTION
**Pull request by adamhathcock**

### CODE REVIEW

**Comment by adamhathcock** [comment]
I wonder if the API has changed...code still seeming works

**Review by alanedwardes — APPROVED** [review]
It wasn't doing a whole lot, would be difficult to break it... we should probably remove the retry from the client libraries and have the consumer add it externally - https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests

a different change though...

**Comment by adamhathcock** [comment]
@alanedwardes did it

**Review by alanedwardes — COMMENTED** [review]
I think we should rip retry completely out of this library (and the other clients), and remove ServiceCollectionExtensions. Then, all a consumer has to do is build their services in their app like...

```csharp
var services = new ServiceCollection();

services.AddSingleton(new SlackConfig{ ... })
services.AddHttpClient<ISlackClient, SlackClient>()
            .AddPolicyHandler(GetRetryPolicy()); // defined in the consumer's code

var provider = services.BuildServiceProvider();

var slackClient = provider.GetRequiredService<ISlackClient>();
```

Then the consumer has full control over all of this - add whatever `DelegatingHandler` middeleware they like, or none at all - and we avoid any versioning issues with packages since the consumer pulls those in.

I can update the README to cover this pattern - but it means this library only needs to depend on `Newtonsoft.Json`, we can get rid of all other dependencies. I really like this because clients become a skeleton wrapper over `HttpClient`, which is really what they should be imo.

WDYT

**Comment by alanedwardes** [comment]
...also if you want to get this out sooner we can just push this as v5 and v6 can be the refactor above (+ I don't mind doing it) 😄

**Comment by adamhathcock** [comment]
Happy to wait for something proper.

I see what you're saying about making the pipeline extendable.  Maybe that's some kind of `Action` option on `AddSlack` but I don't think saying two requires for the ServiceCollection makes sense.

I'll update the PR without Retry options but had a hook to extending the HttpClientHandler pipeline

**Comment by adamhathcock** [comment]
Going to 3.1 now.

**Pull request merged**
